{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "8f64680c",
   "metadata": {},
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8e4ec203",
   "metadata": {},
   "source": [
    "\n",
    "Using the Exception class as the base for custom exceptions ensures compatibility with the standard exception hierarchy and provides necessary functionality for error handling, including methods like __str__() and __repr__(), \n",
    "making it easier to work with and handle custom exceptions."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "be9685fb",
   "metadata": {},
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3c004741",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'Exception'>\n",
      "  <class 'TypeError'>\n",
      "    <class 'email.errors.MultipartConversionError'>\n",
      "    <class 'decimal.FloatOperation'>\n",
      "  <class 'StopAsyncIteration'>\n",
      "  <class 'StopIteration'>\n",
      "  <class 'ImportError'>\n",
      "    <class 'ModuleNotFoundError'>\n",
      "    <class 'zipimport.ZipImportError'>\n",
      "  <class 'OSError'>\n",
      "    <class 'ConnectionError'>\n",
      "      <class 'BrokenPipeError'>\n",
      "      <class 'ConnectionAbortedError'>\n",
      "      <class 'ConnectionRefusedError'>\n",
      "      <class 'ConnectionResetError'>\n",
      "        <class 'http.client.RemoteDisconnected'>\n",
      "    <class 'BlockingIOError'>\n",
      "    <class 'ChildProcessError'>\n",
      "    <class 'FileExistsError'>\n",
      "    <class 'FileNotFoundError'>\n",
      "    <class 'IsADirectoryError'>\n",
      "    <class 'NotADirectoryError'>\n",
      "    <class 'InterruptedError'>\n",
      "      <class 'zmq.error.InterruptedSystemCall'>\n",
      "    <class 'PermissionError'>\n",
      "    <class 'ProcessLookupError'>\n",
      "    <class 'TimeoutError'>\n",
      "    <class 'io.UnsupportedOperation'>\n",
      "    <class 'shutil.Error'>\n",
      "      <class 'shutil.SameFileError'>\n",
      "    <class 'shutil.SpecialFileError'>\n",
      "    <class 'shutil.ExecError'>\n",
      "    <class 'shutil.ReadError'>\n",
      "    <class 'socket.herror'>\n",
      "    <class 'socket.gaierror'>\n",
      "    <class 'socket.timeout'>\n",
      "    <class 'ssl.SSLError'>\n",
      "      <class 'ssl.SSLCertVerificationError'>\n",
      "      <class 'ssl.SSLZeroReturnError'>\n",
      "      <class 'ssl.SSLWantReadError'>\n",
      "      <class 'ssl.SSLWantWriteError'>\n",
      "      <class 'ssl.SSLSyscallError'>\n",
      "      <class 'ssl.SSLEOFError'>\n",
      "    <class 'urllib.error.URLError'>\n",
      "      <class 'urllib.error.HTTPError'>\n",
      "      <class 'urllib.error.ContentTooShortError'>\n",
      "  <class 'EOFError'>\n",
      "    <class 'asyncio.exceptions.IncompleteReadError'>\n",
      "  <class 'RuntimeError'>\n",
      "    <class 'RecursionError'>\n",
      "    <class 'NotImplementedError'>\n",
      "      <class 'IPython.core.error.StdinNotImplementedError'>\n",
      "      <class 'zmq.error.ZMQVersionError'>\n",
      "    <class '_frozen_importlib._DeadlockError'>\n",
      "    <class 'threading.BrokenBarrierError'>\n",
      "    <class 'concurrent.futures._base.BrokenExecutor'>\n",
      "    <class 'asyncio.exceptions.SendfileNotAvailableError'>\n",
      "  <class 'NameError'>\n",
      "    <class 'UnboundLocalError'>\n",
      "  <class 'AttributeError'>\n",
      "  <class 'SyntaxError'>\n",
      "    <class 'IndentationError'>\n",
      "      <class 'TabError'>\n",
      "  <class 'LookupError'>\n",
      "    <class 'IndexError'>\n",
      "    <class 'KeyError'>\n",
      "      <class 'IPython.terminal.pt_inputhooks.UnknownBackend'>\n",
      "      <class 'jupyter_client.kernelspec.NoSuchKernel'>\n",
      "    <class 'encodings.CodecRegistryError'>\n",
      "  <class 'ValueError'>\n",
      "    <class 'UnicodeError'>\n",
      "      <class 'UnicodeEncodeError'>\n",
      "      <class 'UnicodeDecodeError'>\n",
      "      <class 'UnicodeTranslateError'>\n",
      "    <class 'io.UnsupportedOperation'>\n",
      "    <class 'json.decoder.JSONDecodeError'>\n",
      "    <class 'binascii.Error'>\n",
      "    <class 'pygments.util.ClassNotFound'>\n",
      "    <class 'ssl.SSLCertVerificationError'>\n",
      "    <class 'IPython.lib.clipboard.ClipboardEmpty'>\n",
      "    <class 'email.errors.MessageDefect'>\n",
      "      <class 'email.errors.NoBoundaryInMultipartDefect'>\n",
      "      <class 'email.errors.StartBoundaryNotFoundDefect'>\n",
      "      <class 'email.errors.CloseBoundaryNotFoundDefect'>\n",
      "      <class 'email.errors.FirstHeaderLineIsContinuationDefect'>\n",
      "      <class 'email.errors.MisplacedEnvelopeHeaderDefect'>\n",
      "      <class 'email.errors.MissingHeaderBodySeparatorDefect'>\n",
      "      <class 'email.errors.MultipartInvariantViolationDefect'>\n",
      "      <class 'email.errors.InvalidMultipartContentTransferEncodingDefect'>\n",
      "      <class 'email.errors.UndecodableBytesDefect'>\n",
      "      <class 'email.errors.InvalidBase64PaddingDefect'>\n",
      "      <class 'email.errors.InvalidBase64CharactersDefect'>\n",
      "      <class 'email.errors.InvalidBase64LengthDefect'>\n",
      "      <class 'email.errors.HeaderDefect'>\n",
      "        <class 'email.errors.InvalidHeaderDefect'>\n",
      "        <class 'email.errors.HeaderMissingRequiredValue'>\n",
      "        <class 'email.errors.NonPrintableDefect'>\n",
      "        <class 'email.errors.ObsoleteHeaderDefect'>\n",
      "        <class 'email.errors.NonASCIILocalPartDefect'>\n",
      "    <class 'calendar.IllegalMonthError'>\n",
      "    <class 'calendar.IllegalWeekdayError'>\n",
      "    <class 'IPython.core.magics.code.MacroToEdit'>\n",
      "    <class 'dateutil.parser._parser.ParserError'>\n",
      "  <class 'AssertionError'>\n",
      "  <class 'ArithmeticError'>\n",
      "    <class 'FloatingPointError'>\n",
      "    <class 'OverflowError'>\n",
      "    <class 'ZeroDivisionError'>\n",
      "      <class 'decimal.DivisionByZero'>\n",
      "      <class 'decimal.DivisionUndefined'>\n",
      "    <class 'decimal.DecimalException'>\n",
      "      <class 'decimal.Clamped'>\n",
      "      <class 'decimal.Rounded'>\n",
      "        <class 'decimal.Underflow'>\n",
      "        <class 'decimal.Overflow'>\n",
      "      <class 'decimal.Inexact'>\n",
      "        <class 'decimal.Underflow'>\n",
      "        <class 'decimal.Overflow'>\n",
      "      <class 'decimal.Subnormal'>\n",
      "        <class 'decimal.Underflow'>\n",
      "      <class 'decimal.DivisionByZero'>\n",
      "      <class 'decimal.FloatOperation'>\n",
      "      <class 'decimal.InvalidOperation'>\n",
      "        <class 'decimal.ConversionSyntax'>\n",
      "        <class 'decimal.DivisionImpossible'>\n",
      "        <class 'decimal.DivisionUndefined'>\n",
      "        <class 'decimal.InvalidContext'>\n",
      "  <class 'SystemError'>\n",
      "    <class 'encodings.CodecRegistryError'>\n",
      "  <class 'ReferenceError'>\n",
      "  <class 'MemoryError'>\n",
      "  <class 'BufferError'>\n",
      "  <class 'Warning'>\n",
      "    <class 'UserWarning'>\n",
      "      <class 'getpass.GetPassWarning'>\n",
      "      <class 'IPython.core.formatters.FormatterWarning'>\n",
      "    <class 'DeprecationWarning'>\n",
      "      <class 'IPython.core.interactiveshell.ProvisionalWarning'>\n",
      "    <class 'PendingDeprecationWarning'>\n",
      "    <class 'SyntaxWarning'>\n",
      "    <class 'RuntimeWarning'>\n",
      "      <class 'dateutil.parser._parser.UnknownTimezoneWarning'>\n",
      "    <class 'FutureWarning'>\n",
      "      <class 'IPython.core.completer.ProvisionalCompleterWarning'>\n",
      "    <class 'ImportWarning'>\n",
      "    <class 'UnicodeWarning'>\n",
      "    <class 'BytesWarning'>\n",
      "    <class 'ResourceWarning'>\n",
      "    <class 'dateutil.tz.DeprecatedTzFormatWarning'>\n",
      "  <class 'locale.Error'>\n",
      "  <class 'warnings._OptionError'>\n",
      "  <class 'runpy._Error'>\n",
      "  <class 're.error'>\n",
      "  <class 'sre_parse.Verbose'>\n",
      "  <class 'subprocess.SubprocessError'>\n",
      "    <class 'subprocess.CalledProcessError'>\n",
      "    <class 'subprocess.TimeoutExpired'>\n",
      "  <class 'copy.Error'>\n",
      "  <class 'tokenize.TokenError'>\n",
      "  <class 'tokenize.StopTokenizing'>\n",
      "  <class 'zlib.error'>\n",
      "  <class '_lzma.LZMAError'>\n",
      "  <class 'shutil.RegistryError'>\n",
      "  <class 'shutil._GiveupOnFastCopy'>\n",
      "  <class 'inspect.EndOfBlock'>\n",
      "  <class 'traitlets.traitlets.TraitError'>\n",
      "  <class 'argparse.ArgumentError'>\n",
      "  <class 'argparse.ArgumentTypeError'>\n",
      "  <class 'traitlets.config.loader.ConfigError'>\n",
      "    <class 'traitlets.config.loader.ConfigLoaderError'>\n",
      "      <class 'traitlets.config.loader.ArgumentError'>\n",
      "    <class 'traitlets.config.loader.ConfigFileNotFound'>\n",
      "  <class 'traitlets.config.configurable.ConfigurableError'>\n",
      "    <class 'traitlets.config.configurable.MultipleInstanceError'>\n",
      "  <class 'traitlets.config.application.ApplicationError'>\n",
      "  <class 'pydoc.ErrorDuringImport'>\n",
      "  <class 'bdb.BdbQuit'>\n",
      "  <class 'pdb.Restart'>\n",
      "  <class '_ctypes.COMError'>\n",
      "  <class 'ctypes.ArgumentError'>\n",
      "  <class 'struct.error'>\n",
      "  <class 'IPython.utils.process.FindCmdError'>\n",
      "  <class 'IPython.utils.path.HomeDirError'>\n",
      "  <class 'IPython.core.profiledir.ProfileDirError'>\n",
      "  <class 'IPython.core.error.IPythonCoreError'>\n",
      "    <class 'IPython.core.error.TryNext'>\n",
      "    <class 'IPython.core.error.UsageError'>\n",
      "    <class 'IPython.core.error.StdinNotImplementedError'>\n",
      "  <class 'IPython.core.error.InputRejected'>\n",
      "  <class 'getopt.GetoptError'>\n",
      "  <class 'binascii.Incomplete'>\n",
      "  <class 'pygments.util.OptionError'>\n",
      "  <class 'pygments.filters.ErrorToken'>\n",
      "  <class '_pickle.PickleError'>\n",
      "    <class '_pickle.PicklingError'>\n",
      "    <class '_pickle.UnpicklingError'>\n",
      "  <class 'pickle._Stop'>\n",
      "  <class 'IPython.core.prefilter.PrefilterError'>\n",
      "  <class 'IPython.core.alias.AliasError'>\n",
      "    <class 'IPython.core.alias.InvalidAliasError'>\n",
      "  <class 'sqlite3.Error'>\n",
      "    <class 'sqlite3.InterfaceError'>\n",
      "    <class 'sqlite3.DatabaseError'>\n",
      "      <class 'sqlite3.InternalError'>\n",
      "      <class 'sqlite3.OperationalError'>\n",
      "      <class 'sqlite3.ProgrammingError'>\n",
      "      <class 'sqlite3.IntegrityError'>\n",
      "      <class 'sqlite3.DataError'>\n",
      "      <class 'sqlite3.NotSupportedError'>\n",
      "  <class 'sqlite3.Warning'>\n",
      "  <class 'IPython.core.interactiveshell.SpaceInInput'>\n",
      "  <class 'concurrent.futures._base.Error'>\n",
      "    <class 'concurrent.futures._base.CancelledError'>\n",
      "    <class 'concurrent.futures._base.TimeoutError'>\n",
      "    <class 'concurrent.futures._base.InvalidStateError'>\n",
      "  <class 'socket._GiveupOnSendfile'>\n",
      "  <class 'asyncio.exceptions.TimeoutError'>\n",
      "  <class 'asyncio.exceptions.InvalidStateError'>\n",
      "  <class 'asyncio.exceptions.LimitOverrunError'>\n",
      "  <class 'asyncio.queues.QueueEmpty'>\n",
      "  <class 'asyncio.queues.QueueFull'>\n",
      "  <class 'xml.dom.DOMException'>\n",
      "    <class 'xml.dom.IndexSizeErr'>\n",
      "    <class 'xml.dom.DomstringSizeErr'>\n",
      "    <class 'xml.dom.HierarchyRequestErr'>\n",
      "    <class 'xml.dom.WrongDocumentErr'>\n",
      "    <class 'xml.dom.InvalidCharacterErr'>\n",
      "    <class 'xml.dom.NoDataAllowedErr'>\n",
      "    <class 'xml.dom.NoModificationAllowedErr'>\n",
      "    <class 'xml.dom.NotFoundErr'>\n",
      "    <class 'xml.dom.NotSupportedErr'>\n",
      "    <class 'xml.dom.InuseAttributeErr'>\n",
      "    <class 'xml.dom.InvalidStateErr'>\n",
      "    <class 'xml.dom.SyntaxErr'>\n",
      "    <class 'xml.dom.InvalidModificationErr'>\n",
      "    <class 'xml.dom.NamespaceErr'>\n",
      "    <class 'xml.dom.InvalidAccessErr'>\n",
      "    <class 'xml.dom.ValidationErr'>\n",
      "  <class 'prompt_toolkit.validation.ValidationError'>\n",
      "  <class 'prompt_toolkit.buffer.EditReadOnlyBuffer'>\n",
      "  <class 'prompt_toolkit.buffer._Retry'>\n",
      "  <class 'prompt_toolkit.layout.layout.InvalidLayoutError'>\n",
      "  <class 'prompt_toolkit.renderer.HeightIsUnknownError'>\n",
      "  <class '_queue.Empty'>\n",
      "  <class 'queue.Full'>\n",
      "  <class 'parso.parser.ParserSyntaxError'>\n",
      "  <class 'parso.parser.InternalParseError'>\n",
      "  <class 'parso.python.diff._PositionUpdatingFinished'>\n",
      "  <class 'jedi.inference.helpers.SimpleGetItemNotFound'>\n",
      "  <class 'jedi.inference.utils.UncaughtAttributeError'>\n",
      "  <class 'jedi.inference.arguments.ParamIssue'>\n",
      "  <class 'jedi.api.helpers.OnErrorLeaf'>\n",
      "  <class 'jedi.api.exceptions._JediError'>\n",
      "    <class 'jedi.api.exceptions.InternalError'>\n",
      "    <class 'jedi.api.exceptions.WrongVersion'>\n",
      "    <class 'jedi.api.exceptions.RefactoringError'>\n",
      "  <class 'jedi.api.environment.InvalidPythonEnvironment'>\n",
      "  <class 'email.errors.MessageError'>\n",
      "    <class 'email.errors.MessageParseError'>\n",
      "      <class 'email.errors.HeaderParseError'>\n",
      "      <class 'email.errors.BoundaryError'>\n",
      "    <class 'email.errors.MultipartConversionError'>\n",
      "    <class 'email.errors.CharsetError'>\n",
      "  <class 'uu.Error'>\n",
      "  <class 'http.client.HTTPException'>\n",
      "    <class 'http.client.NotConnected'>\n",
      "    <class 'http.client.InvalidURL'>\n",
      "    <class 'http.client.UnknownProtocol'>\n",
      "    <class 'http.client.UnknownTransferEncoding'>\n",
      "    <class 'http.client.UnimplementedFileMode'>\n",
      "    <class 'http.client.IncompleteRead'>\n",
      "    <class 'http.client.ImproperConnectionState'>\n",
      "      <class 'http.client.CannotSendRequest'>\n",
      "      <class 'http.client.CannotSendHeader'>\n",
      "      <class 'http.client.ResponseNotReady'>\n",
      "    <class 'http.client.BadStatusLine'>\n",
      "      <class 'http.client.RemoteDisconnected'>\n",
      "    <class 'http.client.LineTooLong'>\n",
      "  <class 'IPython.core.magics.code.InteractivelyDefined'>\n",
      "  <class 'IPython.terminal.embed.KillEmbedded'>\n",
      "  <class 'zmq.error.ZMQBaseError'>\n",
      "    <class 'zmq.error.ZMQError'>\n",
      "      <class 'zmq.error.ContextTerminated'>\n",
      "      <class 'zmq.error.Again'>\n",
      "      <class 'zmq.error.InterruptedSystemCall'>\n",
      "    <class 'zmq.error.ZMQBindError'>\n",
      "    <class 'zmq.error.NotDone'>\n",
      "  <class 'jupyter_client.localinterfaces.NoIPAddresses'>\n",
      "  <class 'jupyter_client.channels.InvalidPortNumber'>\n",
      "  <class 'jupyter_client.multikernelmanager.DuplicateKernelError'>\n",
      "  <class 'tornado.util.TimeoutError'>\n",
      "  <class 'tornado.concurrent.ReturnValueIgnoredError'>\n",
      "  <class 'tornado.gen.KeyReuseError'>\n",
      "  <class 'tornado.gen.UnknownKeyError'>\n",
      "  <class 'tornado.gen.LeakedCallbackError'>\n",
      "  <class 'tornado.gen.BadYieldError'>\n",
      "  <class 'tornado.gen.ReturnValueIgnoredError'>\n",
      "  <class 'tornado.gen.Return'>\n",
      "  <class 'tornado.queues.QueueEmpty'>\n",
      "  <class 'tornado.queues.QueueFull'>\n",
      "  <class 'pywintypes.error'>\n",
      "  <class 'pywintypes.com_error'>\n",
      "<class 'GeneratorExit'>\n",
      "<class 'SystemExit'>\n",
      "<class 'KeyboardInterrupt'>\n",
      "<class 'asyncio.exceptions.CancelledError'>\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "\n",
    "def print_exception_hierarchy(exceptions, level=0):\n",
    "    for exception in exceptions:\n",
    "        print('  ' * level + str(exception))\n",
    "        if issubclass(exception, BaseException):\n",
    "            print_exception_hierarchy(exception.__subclasses__(), level + 1)\n",
    "\n",
    "print_exception_hierarchy(BaseException.__subclasses__())\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9705360f",
   "metadata": {},
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d98694a0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Division by zero is not allowed.\n"
     ]
    }
   ],
   "source": [
    "#ZeroDivisionError: This exception is raised when division or modulo \n",
    "#operation is performed with zero as the divisor. It occurs when an attempt is made to divide a number by zero\n",
    "numerator = 10\n",
    "denominator = 0\n",
    "\n",
    "try:\n",
    "    result = numerator / denominator\n",
    "    print(\"Result:\", result)\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Division by zero is not allowed.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2f1a880f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Value: 9223372036854775808\n"
     ]
    }
   ],
   "source": [
    "#OverflowError: This exception is raised when an arithmetic calculation results in a value\n",
    "#that exceeds the maximum representable value for a specific numeric type. \n",
    "#t typically occurs when performing calculations that lead to excessively large numbers.\n",
    "\n",
    "import sys\n",
    "\n",
    "try:\n",
    "    value = sys.maxsize + 1\n",
    "    print(\"Value:\", value)\n",
    "except OverflowError:\n",
    "    print(\"Error: Arithmetic operation resulted in an overflow.\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c1dea796",
   "metadata": {},
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "30d1a03b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Key not found in the dictionary.\n"
     ]
    }
   ],
   "source": [
    "#KeyError: This exception is raised when a dictionary key is not found during a lookup operation. \n",
    "#It occurs when an attempt is made to access a dictionary using a key that does not exist.\n",
    "dictionary = {'a': 1, 'b': 2, 'c': 3}\n",
    "\n",
    "try:\n",
    "    value = dictionary['d']\n",
    "    print(\"Value:\", value)\n",
    "except KeyError:\n",
    "    print(\"Error: Key not found in the dictionary.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "fc38d28f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Index is out of range for the sequence.\n"
     ]
    }
   ],
   "source": [
    "#IndexError: This exception is raised when a sequence (such as a list or a string) index is out of range.\n",
    "#It occurs when an attempt is made to access an element from a sequence using an invalid index value\n",
    "\n",
    "sequence = [1, 2, 3]\n",
    "\n",
    "try:\n",
    "    value = sequence[3]\n",
    "    print(\"Value:\", value)\n",
    "except IndexError:\n",
    "    print(\"Error: Index is out of range for the sequence.\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5ae8a0f6",
   "metadata": {},
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "b7e6b633",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Module not found or cannot be imported.\n"
     ]
    }
   ],
   "source": [
    "#ImportError: This exception is raised when an error occurs during the import process. \n",
    "#It can occur in various situations, such as when a module or attribute is not found,\n",
    "#when there are issues with module dependencies or circular imports, or when there are problems with the Python environment setup\n",
    "\n",
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError:\n",
    "    print(\"Error: Module not found or cannot be imported.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "34f44a0d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Module not found.\n"
     ]
    }
   ],
   "source": [
    "#ModuleNotFoundError: Starting from Python 3.6, the ModuleNotFoundError exception is a subclass of ImportError. \n",
    "#It is specifically raised when a module or package cannot be found during the import process. \n",
    "#It provides a more precise error message to indicate that the specific module or package was not found.\n",
    "\n",
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError:\n",
    "    print(\"Error: Module not found.\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1449a06d",
   "metadata": {},
   "source": [
    "Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "56388956",
   "metadata": {},
   "source": [
    "Best practices for exception handling in Python include catching specific exceptions, using multiple except blocks,\n",
    "avoiding global exception handling, utilizing the finally block for cleanup, \n",
    "avoiding bare except statements, and providing meaningful error messages for debugging and troubleshooting."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a8414766",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
